In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Predicting for DataSet4**


In [2]:
df4 = pd.read_csv('/kaggle/input/dataset4/Data4.csv')

In [3]:
df4

Sl.    x1         x2         x3           y
0     1   0.1   0.311089   0.390541   14.705876
1     2   0.2   0.639066   1.389918   26.585100
2     3   0.3   0.840228   1.939903   36.791509
3     4   0.4   1.299710   2.153009   34.090806
4     5   0.5   0.941784   0.945136   31.118089
..  ...   ...        ...        ...         ...
95   96   9.6  10.336087   9.979673  183.744594
96   97   9.7   9.928599  10.721891  175.907274
97   98   9.8  10.109046  10.163445  183.992845
98   99   9.9   9.954540  10.562039  173.920425
99  100  10.0  10.469087  10.727984  179.018755

[100 rows x 5 columns]

In [4]:
c = 0.2

In [5]:
y = df4['y']

In [6]:
y_array = np.array(y)

In [7]:
y_array[0]

14.7058762

In [8]:
df4 = df4.drop(columns='y')
df4 = df4.drop(columns='Sl.')

In [9]:
df4

x1         x2         x3
0    0.1   0.311089   0.390541
1    0.2   0.639066   1.389918
2    0.3   0.840228   1.939903
3    0.4   1.299710   2.153009
4    0.5   0.941784   0.945136
..   ...        ...        ...
95   9.6  10.336087   9.979673
96   9.7   9.928599  10.721891
97   9.8  10.109046  10.163445
98   9.9   9.954540  10.562039
99  10.0  10.469087  10.727984

[100 rows x 3 columns]

In [10]:
n = df4.shape[1]
print(n)

3


In [11]:
A = np.zeros((n,n))
for i in range(len(df4)):
    r = np.array(df4.iloc[i])
    a1 = r.reshape((n, 1))
    a2 = a1.T
#     print(a1, a2)
    A += a1@a2

print("Resulting Matrix A:")
print(A)

Resulting Matrix A:
[[3383.5        3641.01643904 3863.4271195 ]
 [3641.01643904 3929.68278392 4171.37422047]
 [3863.4271195  4171.37422047 4472.48767615]]


In [12]:
A_inv = np.linalg.inv(A)

print("Original Matrix A:")
print(A)

print("\nInverse of Matrix A:")
print(A_inv)

Original Matrix A:
[[3383.5        3641.01643904 3863.4271195 ]
 [3641.01643904 3929.68278392 4171.37422047]
 [3863.4271195  4171.37422047 4472.48767615]]

Inverse of Matrix A:
[[ 0.10108392 -0.09733483  0.00346332]
 [-0.09733483  0.11926801 -0.02715837]
 [ 0.00346332 -0.02715837  0.02256181]]


In [13]:
# b = summation of (X_i*Y_i) from i = 0 to n

b = np.zeros((n,1))

for i in range(len(df4)):
    r = np.array(df4.iloc[i])
    b1 = r.reshape((n,1))
    b2 = y_array[i].reshape((1,1))
    b += b1@b2
    
print(b)

[[66074.55450872]
 [71379.27277894]
 [76343.57296322]]


In [14]:
w = A_inv@b
print(w.T)

[[-4.21240322  8.54119794 12.74220457]]


In [15]:
def predict(df):
    lst = []
    for i in range(len(df)):
        lst.append(w.T @ np.array(df.iloc[i][:]) + c)
    return lst

In [16]:
df4

x1         x2         x3
0    0.1   0.311089   0.390541
1    0.2   0.639066   1.389918
2    0.3   0.840228   1.939903
3    0.4   1.299710   2.153009
4    0.5   0.941784   0.945136
..   ...        ...        ...
95   9.6  10.336087   9.979673
96   9.7   9.928599  10.721891
97   9.8  10.109046  10.163445
98   9.9   9.954540  10.562039
99  10.0  10.469087  10.727984

[100 rows x 3 columns]

In [17]:
df4['predicted'] = predict(df4)

In [18]:
df4['y'] = y_array

In [19]:
df4

x1         x2         x3             predicted           y
0    0.1   0.311089   0.390541   [7.412189896215797]   14.705876
1    0.2   0.639066   1.389918   [22.52653494064627]   26.585100
2    0.3   0.840228   1.939903   [30.83146967374577]   36.791509
3    0.4   1.299710   2.153009   [37.05020832980665]   34.090806
4    0.5   0.941784   0.945136  [18.180877686862235]   31.118089
..   ...        ...        ...                   ...         ...
95   9.6  10.336087   9.979673   [175.2065285467928]  183.744594
96   9.7   9.928599  10.721891   [180.7623546554319]  175.907274
97   9.8  10.109046  10.163445  [174.76649965170452]  183.992845
98   9.9   9.954540  10.562039  [178.10456140432942]  173.920425
99  10.0  10.469087  10.727984  [184.19267595968137]  179.018755

[100 rows x 5 columns]

In [20]:
def R2(df):
  return 1 - Rss(df) / Tss(df)

In [21]:
def Rss(df):
  return np.sum((df['y'] - df['predicted']) ** 2)

In [22]:
def Tss(df):
  return np.sum((df['y'] - np.mean(df['predicted']))** 2)

In [23]:
R2(df4)

array([0.97750659])

In [24]:
df4

x1         x2         x3             predicted           y
0    0.1   0.311089   0.390541   [7.412189896215797]   14.705876
1    0.2   0.639066   1.389918   [22.52653494064627]   26.585100
2    0.3   0.840228   1.939903   [30.83146967374577]   36.791509
3    0.4   1.299710   2.153009   [37.05020832980665]   34.090806
4    0.5   0.941784   0.945136  [18.180877686862235]   31.118089
..   ...        ...        ...                   ...         ...
95   9.6  10.336087   9.979673   [175.2065285467928]  183.744594
96   9.7   9.928599  10.721891   [180.7623546554319]  175.907274
97   9.8  10.109046  10.163445  [174.76649965170452]  183.992845
98   9.9   9.954540  10.562039  [178.10456140432942]  173.920425
99  10.0  10.469087  10.727984  [184.19267595968137]  179.018755

[100 rows x 5 columns]

In [25]:
y = df4['y']

In [26]:
df4 = df4.drop(columns='y')
df4 = df4.drop(columns='predicted')

In [27]:
df4

x1         x2         x3
0    0.1   0.311089   0.390541
1    0.2   0.639066   1.389918
2    0.3   0.840228   1.939903
3    0.4   1.299710   2.153009
4    0.5   0.941784   0.945136
..   ...        ...        ...
95   9.6  10.336087   9.979673
96   9.7   9.928599  10.721891
97   9.8  10.109046  10.163445
98   9.9   9.954540  10.562039
99  10.0  10.469087  10.727984

[100 rows x 3 columns]

***Verify using Scikit Learn***

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()

In [29]:
X = df4[['x1', 'x2', 'x3']]
lr.fit(X,y)

LinearRegression()

In [30]:
y_predict = lr.predict(X)

In [31]:
r_squared = r2_score(y, y_predict)
print(r_squared)

0.9841749058943147
